apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-blue
  namespace: default
  labels:
    app: movie-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-app-blue
  template:
    metadata:
      labels:
        app: movie-app-blue
    spec:
      containers:
      - name: movie-app
        image: adityao9/movie-app:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
