apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
  namespace: default
spec:
  selector:
    app: movie-app-blue  # initial deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
