apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
spec:
  type: NodePort
  selector:
    app: movie-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080