apiVersion: v1
kind: Service
metadata:
  name: movie-app-service
spec:
  type: LoadBalancer
  selector:
    app: movie-app-blue  # Initially blue deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
